//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Vcc.rc
//
/*
Copyright 2015 by Joseph Forgione
This file is part of VCC (Virtual Color Computer).

    VCC (Virtual Color Computer) is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    VCC (Virtual Color Computer) is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with VCC (Virtual Color Computer).  If not, see <http://www.gnu.org/licenses/>.
*/


#define IDS_APP_TITLE                   1
#define IDS_CATNUMBER                   2
#define IDAPPLY                         3
#define IDR_MENU                        101
#define IDI_COCO3                       103
#define IDD_ABOUTBOX                    104
#define IDD_CONFIG                      105
#define IDD_DISKS                       106
#define IDB_VCC                         108
#define IDI_BINFILE                     110
#define IDB_BENDER                      111
#define IDI_CART                        112
#define IDC_NONE                        113
#define IDI_MOTO                        114
#define IDI_HITACHI2                    116
#define IDI_COMPOSITE                   117
#define IDI_RGB                         118
#define IDC_CURSOR1                     120
#define IDB_NOMUTE                      128
#define IDB_MUTE                        130
#define IDD_KEYBOARD                    134
#define IDD_TCONFIG                     135
#define IDD_DISPLAY                     136
#define IDD_CPU                         137
#define IDD_AUDIO                       138
#define IDD_INPUT                       139
#define IDD_JOYSTICK                    141
#define IDI_AUDIO                       146
#define IDI_KEYBOARD                    148
#define IDI_JOYSTICK                    149
#define IDI_MOUSE                       150
#define IDD_MISC                        154
#define IDB_3GUYS                       156
#define IDD_CASSETTE                    157
#define IDD_NEWTAPE                     158
#define IDD_BITBANGER                   159
#define IDC_MUTE                        1003
#define IDC_THROTTLE                    1004
#define IDC_ARTIFACTS                   1005
#define IDC_128K                        1006
#define IDC_512K                        1007
#define IDC_2M                          1008
#define IDC_8M                          1009
#define IDC_CLOCKSPEED                  1011
#define IDC_CLOCKDISPLAY                1012
#define IDC_RGBMON                      1013
#define IDC_FRAMESKIP                   1014
#define IDC_FRAMEDISPLAY                1015
#define IDC_RADIO1                      1016
#define IDC_6809                        1016
#define IDC_LEFT_KEYBOARD               1016
#define IDC_RADIO2                      1017
#define IDC_6309                        1017
#define IDC_LEFTJOYSTICK                1017
#define IDC_RADIO3                      1018
#define IDC_RGB                         1018
#define IDC_LEFTAUDIO                   1018
#define IDC_EDIT1                       1019
#define IDC_RIGHTJOYSTICK               1019
#define IDC_TCOUNT                      1019
#define IDC_SERIALFILE                  1019
#define IDC_EDIT2                       1020
#define IDC_RIGHTAUDIO                  1020
#define IDC_TAPEFILE                    1020
#define IDC_EDIT3                       1021
#define IDC_LEFT_USEMOUSE               1021
#define IDC_MODE                        1021
#define IDC_RADIO4                      1022
#define IDC_COMPOSITE                   1022
#define IDC_RIGHT_KEYBOARD              1022
#define IDC_EDIT4                       1023
#define IDC_BUTTON1                     1024
#define IDC_Q                           1024
#define IDC_PLAY                        1024
#define IDC_OPEN                        1024
#define IDC_BUTTON2                     1025
#define IDC_RGBDOS                      1025
#define IDC_W                           1025
#define IDC_REC                         1025
#define IDC_CLOSE                       1025
#define IDC_BUTTON3                     1026
#define IDC_TITLE                       1026
#define IDC_E                           1026
#define IDC_RESET                       1026
#define IDC_SCANLINES                   1027
#define IDC_R                           1027
#define IDC_STOP                        1027
#define IDC_INVERT                      1028
#define IDC_T                           1028
#define IDC_EJECT                       1028
#define IDC_CPUTYPE                     1029
#define IDC_Y                           1029
#define IDC_ASPECT                      1030
#define IDC_U                           1030
#define IDC_RESIZE                      1031
#define IDC_I                           1031
#define IDC_AUTOSTART                   1032
#define IDC_O                           1032
#define IDC_CPUICON                     1033
#define IDC_P                           1033
#define IDC_MONTYPE                     1034
#define IDC_LBRACE                      1034
#define IDC_RBRACE                      1035
#define IDC_PIPE                        1036
#define IDC_CONFIGTAB                   1036
#define IDC_A                           1037
#define IDC_S                           1038
#define IDC_D                           1039
#define IDC_COMBO1                      1039
#define IDC_LEFT_LEFT                   1039
#define IDC_SOUNDCARD                   1039
#define IDC_KBCONFIG                    1039
#define IDC_F                           1040
#define IDC_LEFT_RIGHT                  1040
#define IDC_G                           1041
#define IDC_LEFT_UP                     1041
#define IDC_H                           1042
#define IDC_LEFT_DOWN                   1042
#define IDC_J                           1043
#define IDC_K                           1044
#define IDC_L                           1045
#define IDC_LEFT_FIRE1                  1045
#define IDC_SEMI                        1046
#define IDC_LEFT_FIRE2                  1046
#define IDC_QUOTE                       1047
#define IDC_RIGHT_LEFT                  1047
#define IDC_RIGHT_RIGHT                 1048
#define IDC_ENTER                       1049
#define IDC_RIGHT_UP                    1049
#define IDC_RIGHT_DOWN                  1050
#define IDC_RIGHT_FIRE1                 1051
#define IDC_RIGHT_FIRE2                 1052
#define IDC_Z                           1053
#define IDC_LEFTAUDIODEVICE             1053
#define IDC_X                           1054
#define IDC_LEFTJOYSTICKDEVICE          1054
#define IDC_C                           1055
#define IDC_RIGHTAUDIODEVICE            1055
#define IDC_V                           1056
#define IDC_RIGHTJOYSTICKDEVICE         1056
#define IDC_B                           1057
#define IDC_RIGHT_USEMOUSE              1057
#define IDC_N                           1058
#define IDC_LEFTICON                    1058
#define IDC_M                           1059
#define IDC_RIGHTICON                   1059
#define IDC_COMMA                       1060
#define IDC_AUTOCART                    1060
#define IDC_PERIOD                      1061
#define IDC_RATE                        1061
#define IDC_FS                          1062
#define IDC_PROGRESSLEFT                1062
#define IDC_PROGRESSRIGHT               1063
#define IDC_RSHIFT                      1064
#define IDC_SPIN2                       1064
#define IDC_LSHIFT                      1065
#define IDC_BROWSE                      1065
#define IDC_TBROWSE                     1065
#define IDC_CAPS                        1066
#define IDC_TAB                         1067
#define IDC_SPACE                       1068
#define IDC_LCTRL                       1069
#define IDC_RADIO5                      1069
#define IDC_LALT                        1070
#define IDC_LF                          1070
#define IDC_RCTRL                       1071
#define IDC_PRINTMON                    1071
#define IDC_RALT                        1072
#define IDC_1                           1073
#define IDC_2                           1074
#define IDC_3                           1075
#define IDC_4                           1076
#define IDC_5                           1077
#define IDC_6                           1078
#define IDC_7                           1079
#define IDC_8                           1080
#define IDC_9                           1081
#define IDC_0                           1082
#define IDC_MINUS                       1083
#define IDC_EQUL                        1084
#define IDC_BACKSPACE                   1085
#define IDC_LQUOTE                      1086
#define IDC_F2                          1087
#define IDC_F3                          1088
#define IDC_F4                          1089
#define IDC_F5                          1090
#define IDC_F6                          1091
#define IDC_F7                          1092
#define IDC_F8                          1093
#define IDC_F9                          1094
#define IDC_F10                         1095
#define IDC_F11                         1096
#define IDC_F12                         1097
#define IDC_INS                         1098
#define IDC_F1                          1099
#define IDC_HOME                        1100
#define IDC_PGUP                        1101
#define IDC_DEL                         1102
#define IDC_END                         1103
#define IDC_EQUL7                       1104
#define IDC_UP                          1105
#define IDC_RIGHT                       1106
#define IDC_DOWN                        1107
#define IDC_LEFT                        1108
#define IDC_Q2                          1109
#define IDC_W2                          1110
#define IDC_E2                          1111
#define IDC_R2                          1112
#define IDC_T2                          1113
#define IDC_Y2                          1114
#define IDC_U2                          1115
#define IDC_I2                          1116
#define IDC_O2                          1117
#define IDC_P2                          1118
#define IDC_AT                          1119
#define IDC_CLEAR                       1120
#define IDC_A2                          1122
#define IDC_S2                          1123
#define IDC_D2                          1124
#define IDC_F13                         1125
#define IDC_G2                          1126
#define IDC_H2                          1127
#define IDC_J2                          1128
#define IDC_K2                          1129
#define IDC_L2                          1130
#define IDC_SEMI2                       1131
#define IDC_ENTER2                      1133
#define IDC_Z2                          1134
#define IDC_X2                          1135
#define IDC_C2                          1136
#define IDC_V2                          1137
#define IDC_B2                          1138
#define IDC_N2                          1139
#define IDC_M2                          1140
#define IDC_COMMA2                      1141
#define IDC_PERIOD2                     1142
#define IDC_FS2                         1143
#define IDC_RSHIFT2                     1144
#define IDC_LSHIFT2                     1145
#define IDC_SPACE2                      1148
#define IDC_LCTRL2                      1149
#define IDC_LALT2                       1150
#define IDC_10                          1153
#define IDC_11                          1154
#define IDC_12                          1155
#define IDC_13                          1156
#define IDC_14                          1157
#define IDC_15                          1158
#define IDC_16                          1159
#define IDC_17                          1160
#define IDC_18                          1161
#define IDC_19                          1162
#define IDC_COLON2                      1163
#define IDC_MINUS2                      1164
#define IDC_BREAK                       1165
#define IDC_F14                         1167
#define IDC_F15                         1168
#define IDC_LEFT2                       1169
#define IDC_RIGHT2                      1170
#define IDC_DOWN2                       1171
#define IDC_UP2                         1172
#define ID_FILE_EXIT                    40002
#define IDM_HELP_ABOUT                  40003
#define ID_FILE_RUN                     40004
#define ID_FILE_RESET                   40005
#define ID_CARTS_LOAD                   40006
#define ID_DISKS_DRIVE0                 40007
#define ID_DISKS_DRIVE1                 40008
#define ID_DISKS_DRIVE2                 40009
#define ID_DISKS_DRIVE3                 40010
#define ID_DISKS_HD                     40010
#define ID_FILE_RESET_SFT               40011
#define ID_DUMPMEM                      40012
#define ID_CONSOLE                      40013
#define ID_CPUDUMP                      40014
#define ID_RBUTTON                      40015
#define ID_LBUTTON                      40016
#define ID_DISKS_DRIVE0_UNMOUNT         40018
#define ID_DISKS_DRIVE1_UNMOUNT         40019
#define ID_DISKS_DRIVE2_UNMOUNT         40020
#define ID_DISKS_HARDDRIVE_UNMOUNT      40021
#define ID_QUICK                        40022
#define ID_IRQ                          40023
#define ID_FIRQ                         40024
#define ID_NMI                          40025
#define ID_CARTRIDGE_INSERT             40026
#define ID_FILE_LOAD                    40028
#define ID_CARTS_EJECT                  40030
#define ID_CONFIGURE_OPTIONS            65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         40031
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
