//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Vcc.rc
//
#define IDS_APP_TITLE                   1
#define IDS_CATNUMBER                   2
#define IDAPPLY                         3
#define IDOK2                           3
#define IDR_MENU                        101
#define IDI_COCO3                       103
#define IDD_ABOUTBOX                    104
#define IDD_CONFIG                      105
#define IDD_DISKS                       106
#define IDB_VCC                         108
#define IDI_BINFILE                     110
#define IDB_BENDER                      111
#define IDI_CART                        112
#define IDC_NONE                        113
#define IDI_MOTO                        114
#define IDI_HITACHI2                    116
#define IDI_COMPOSITE                   117
#define IDI_RGB                         118
#define IDC_CURSOR1                     120
#define IDB_NOMUTE                      128
#define IDB_MUTE                        130
#define IDD_KEYBOARD                    134
#define IDD_TCONFIG                     135
#define IDD_DISPLAY                     136
#define IDD_CPU                         137
#define IDD_AUDIO                       138
#define IDD_INPUT                       139
#define IDD_JOYSTICK                    141
#define IDI_AUDIO                       146
#define IDI_KEYBOARD                    148
#define IDI_JOYSTICK                    149
#define IDI_MOUSE                       150
#define IDD_MISC                        154
#define IDB_3GUYS                       156
#define IDD_CASSETTE                    157
#define IDD_NEWTAPE                     158
#define IDD_BITBANGER                   159
#define IDD_KEYMAPEDIT                  164
#define IDD_DIALOG1                     169
#define IDC_MUTE                        1003
#define IDC_THROTTLE                    1004
#define IDC_ARTIFACTS                   1005
#define IDC_128K                        1006
#define IDC_512K                        1007
#define IDC_2M                          1008
#define IDC_8M                          1009
#define IDC_CLOCKSPEED                  1011
#define IDC_CLOCKDISPLAY                1012
#define IDC_RGBMON                      1013
#define IDC_FRAMESKIP                   1014
#define IDC_FRAMEDISPLAY                1015
#define IDC_RADIO1                      1016
#define IDC_6809                        1016
#define IDC_LEFT_KEYBOARD               1016
#define IDC_RADIO2                      1017
#define IDC_6309                        1017
#define IDC_LEFTJOYSTICK                1017
#define IDC_RADIO3                      1018
#define IDC_RGB                         1018
#define IDC_LEFTAUDIO                   1018
#define IDC_EDIT1                       1019
#define IDC_RIGHTJOYSTICK               1019
#define IDC_TCOUNT                      1019
#define IDC_SERIALFILE                  1019
#define IDC_EDIT2                       1020
#define IDC_RIGHTAUDIO                  1020
#define IDC_TAPEFILE                    1020
#define IDC_EDIT3                       1021
#define IDC_LEFT_USEMOUSE               1021
#define IDC_MODE                        1021
#define IDC_RADIO4                      1022
#define IDC_COMPOSITE                   1022
#define IDC_RIGHT_KEYBOARD              1022
#define IDC_EDIT4                       1023
#define IDC_BUTTON1                     1024
#define IDC_Q                           1024
#define IDC_PLAY                        1024
#define IDC_OPEN                        1024
#define IDC_BUTTON2                     1025
#define IDC_RGBDOS                      1025
#define IDC_W                           1025
#define IDC_REC                         1025
#define IDC_CLOSE                       1025
#define IDC_BUTTON3                     1026
#define IDC_TITLE                       1026
#define IDC_E                           1026
#define IDC_RESET                       1026
#define IDC_SCANLINES                   1027
#define IDC_R                           1027
#define IDC_STOP                        1027
#define IDC_BUTTON4                     1027
#define IDC_INVERT                      1028
#define IDC_T                           1028
#define IDC_EJECT                       1028
#define IDC_BUTTON5                     1028
#define IDC_CPUTYPE                     1029
#define IDC_Y                           1029
#define IDC_BUTTON6                     1029
#define IDC_ASPECT                      1030
#define IDC_U                           1030
#define IDC_BUTTON7                     1030
#define IDC_RESIZE                      1031
#define IDC_I                           1031
#define IDC_BUTTON8                     1031
#define IDC_AUTOSTART                   1032
#define IDC_O                           1032
#define IDC_BUTTON9                     1032
#define IDC_CPUICON                     1033
#define IDC_P                           1033
#define IDC_BUTTON10                    1033
#define IDC_MONTYPE                     1034
#define IDC_LBRACE                      1034
#define IDC_BUTTON11                    1034
#define IDC_RBRACE                      1035
#define IDC_BUTTON12                    1035
#define IDC_PIPE                        1036
#define IDC_CONFIGTAB                   1036
#define IDC_BUTTON13                    1036
#define IDC_A                           1037
#define IDC_BUTTON14                    1037
#define IDC_S                           1038
#define IDC_BUTTON15                    1038
#define IDC_D                           1039
#define IDC_COMBO1                      1039
#define IDC_LEFT_LEFT                   1039
#define IDC_SOUNDCARD                   1039
#define IDC_KBCONFIG                    1039
#define IDC_BUTTON16                    1039
#define IDC_F                           1040
#define IDC_LEFT_RIGHT                  1040
#define IDC_BUTTON17                    1040
#define IDC_G                           1041
#define IDC_LEFT_UP                     1041
#define IDC_BUTTON18                    1041
#define IDC_H                           1042
#define IDC_LEFT_DOWN                   1042
#define IDC_BUTTON19                    1042
#define IDC_J                           1043
#define IDC_BUTTON20                    1043
#define IDC_K                           1044
#define IDC_BUTTON21                    1044
#define IDC_L                           1045
#define IDC_LEFT_FIRE1                  1045
#define IDC_BUTTON22                    1045
#define IDC_SEMI                        1046
#define IDC_LEFT_FIRE2                  1046
#define IDC_BUTTON23                    1046
#define IDC_QUOTE                       1047
#define IDC_RIGHT_LEFT                  1047
#define IDC_BUTTON24                    1047
#define IDC_RIGHT_RIGHT                 1048
#define IDC_BUTTON25                    1048
#define IDC_ENTER                       1049
#define IDC_RIGHT_UP                    1049
#define IDC_BUTTON26                    1049
#define IDC_RIGHT_DOWN                  1050
#define IDC_BUTTON27                    1050
#define IDC_RIGHT_FIRE1                 1051
#define IDC_BUTTON28                    1051
#define IDC_RIGHT_FIRE2                 1052
#define IDC_BUTTON29                    1052
#define IDC_Z                           1053
#define IDC_LEFTAUDIODEVICE             1053
#define IDC_BUTTON30                    1053
#define IDC_X                           1054
#define IDC_LEFTJOYSTICKDEVICE          1054
#define IDC_BUTTON31                    1054
#define IDC_C                           1055
#define IDC_RIGHTAUDIODEVICE            1055
#define IDC_BUTTON32                    1055
#define IDC_V                           1056
#define IDC_RIGHTJOYSTICKDEVICE         1056
#define IDC_BUTTON33                    1056
#define IDC_B                           1057
#define IDC_RIGHT_USEMOUSE              1057
#define IDC_BUTTON34                    1057
#define IDC_N                           1058
#define IDC_LEFTICON                    1058
#define IDC_BUTTON35                    1058
#define IDC_M                           1059
#define IDC_RIGHTICON                   1059
#define IDC_BUTTON36                    1059
#define IDC_COMMA                       1060
#define IDC_AUTOCART                    1060
#define IDC_BUTTON37                    1060
#define IDC_PERIOD                      1061
#define IDC_RATE                        1061
#define IDC_BUTTON38                    1061
#define IDC_FS                          1062
#define IDC_PROGRESSLEFT                1062
#define IDC_BUTTON39                    1062
#define IDC_PROGRESSRIGHT               1063
#define IDC_BUTTON40                    1063
#define IDC_RSHIFT                      1064
#define IDC_SPIN2                       1064
#define IDC_BUTTON41                    1064
#define IDC_LSHIFT                      1065
#define IDC_BROWSE                      1065
#define IDC_TBROWSE                     1065
#define IDC_BUTTON42                    1065
#define IDC_CAPS                        1066
#define IDC_BUTTON43                    1066
#define IDC_TAB                         1067
#define IDC_BUTTON44                    1067
#define IDC_SPACE                       1068
#define IDC_BUTTON45                    1068
#define IDC_LCTRL                       1069
#define IDC_RADIO5                      1069
#define IDC_BUTTON46                    1069
#define IDC_LALT                        1070
#define IDC_LF                          1070
#define IDC_RIGHTSTANDARD               1070
#define IDC_BUTTON47                    1070
#define IDC_RCTRL                       1071
#define IDC_PRINTMON                    1071
#define IDC_LEFTSTANDARD                1071
#define IDC_BUTTON48                    1071
#define IDC_RALT                        1072
#define IDC_BUTTON49                    1072
#define IDC_1                           1073
#define IDC_BUTTON50                    1073
#define IDC_2                           1074
#define IDC_RIGHTTHRES                  1074
#define IDC_BUTTON51                    1074
#define IDC_3                           1075
#define IDC_RIGHTCCMAX                  1075
#define IDC_BUTTON52                    1075
#define IDC_4                           1076
#define IDC_LEFTTHIRES                  1076
#define IDC_BUTTON53                    1076
#define IDC_5                           1077
#define IDC_RADIO11                     1077
#define IDC_LEFTCCMAX                   1077
#define IDC_BUTTON54                    1077
#define IDC_6                           1078
#define IDC_BUTTON55                    1078
#define IDC_7                           1079
#define IDC_BUTTON56                    1079
	
#define IDC_KEYMAPED					1090
// IDC_KEYBTN_FIRST must point to the lowest CoCo KEYBTN Id
// IDC_KEYBTN_LAST must point to the highest CoCo KEYBTN Id
#define IDC_KEYBTN_FIRST                1092
#define IDC_KEYBTN_1                    1092
#define IDC_KEYBTN_2                    1093
#define IDC_KEYBTN_3                    1094
#define IDC_KEYBTN_4                    1095
#define IDC_KEYBTN_5                    1096
#define IDC_KEYBTN_6                    1097
#define IDC_KEYBTN_7                    1098
#define IDC_KEYBTN_8                    1099
#define IDC_KEYBTN_9                    1100
#define IDC_KEYBTN_0                    1101
#define IDC_KEYBTN_COLON                1102
#define IDC_KEYBTN_MINUS                1103
#define IDC_KEYBTN_BRK                  1104
#define IDC_KEYBTN_Q                    1105
#define IDC_KEYBTN_W                    1106
#define IDC_KEYBTN_R                    1107
#define IDC_KEYBTN_T                    1108
#define IDC_KEYBTN_Y                    1109
#define IDC_KEYBTN_U                    1110
#define IDC_KEYBTN_I                    1111
#define IDC_KEYBTN_O                    1112
#define IDC_KEYBTN_P                    1113
#define IDC_KEYBTN_AT                   1114
#define IDC_KEYBTN_CLR                  1115
#define IDC_KEYBTN_UP                   1116
#define IDC_KEYBTN_A                    1117
#define IDC_KEYBTN_S                    1119
#define IDC_KEYBTN_D                    1120
#define IDC_KEYBTN_F                    1121
#define IDC_KEYBTN_G                    1122
#define IDC_KEYBTN_H                    1123
#define IDC_KEYBTN_J                    1124
#define IDC_KEYBTN_K                    1125
#define IDC_KEYBTN_L                    1126
#define IDC_KEYBTN_SEMI                 1127
#define IDC_KEYBTN_ENTER                1128
#define IDC_KEYBTN_LEFT                 1129
#define IDC_KEYBTN_RIGHT                1130
#define IDC_KEYBTN_Z                    1131
#define IDC_KEYBTN_X                    1132
#define IDC_KEYBTN_C        			1133
#define IDC_KEYBTN_E                    1134
#define IDC_KEYBTN_B                    1135
#define IDC_KEYBTN_N                    1136
#define IDC_KEYBTN_M                    1137
#define IDC_KEYBTN_COMMA                1138
#define IDC_KEYBTN_PERIOD               1139
#define IDC_KEYBTN_SLASH                1140
#define IDC_KEYBTN_V                    1141
#define IDC_KEYBTN_DOWN                 1142
#define IDC_KEYBTN_SPACE                1143
#define IDC_KEYBTN_F1                   1144
#define IDC_KEYBTN_F2                   1145
// Modifiers must be at tail of CoCo key buttons
#define IDC_KEYBTN_ALT                  1146
#define IDC_KEYBTN_CTRL                 1147
#define IDC_KEYBTN_RSHIFT               1148
#define IDC_KEYBTN_LSHIFT               1149
#define IDC_KEYBTN_LAST                 1149

// Other key map editor controls
#define IDC_SELECT_KEYMAP               1150
#define IDC_KEYMAP_OK                   1152
#define IDC_SET_CUST_KEYMAP             1153
#define IDC_PCKEY_TXT                   1155
#define IDC_CCKEY_TXT                   1156
#define IDC_KEYMAP_FILE                 1157

#define IDC_KEYMAP_COCO                 1158
#define IDC_KEYMAP_NATURAL              1159
#define IDC_KEYMAP_COMPACT              1160
#define IDC_KEYMAP_CUSTOM               1170
// End keymapedit

#define IDC_ORG_PALETTE                 1191
#define IDC_UPD_PALETTE                 1192

#define ID_FILE_EXIT                    40002
#define IDM_HELP_ABOUT                  40003
#define ID_FILE_RUN                     40004
#define ID_FILE_RESET                   40005
#define ID_CARTS_LOAD                   40006
#define ID_DISKS_DRIVE0                 40007
#define ID_DISKS_DRIVE1                 40008
#define ID_DISKS_DRIVE2                 40009
#define ID_DISKS_DRIVE3                 40010
#define ID_DISKS_HD                     40010
#define ID_FILE_RESET_SFT               40011
#define ID_DUMPMEM                      40012
#define ID_CONSOLE                      40013
#define ID_CPUDUMP                      40014
#define ID_RBUTTON                      40015
#define ID_LBUTTON                      40016
#define ID_DISKS_DRIVE0_UNMOUNT         40018
#define ID_DISKS_DRIVE1_UNMOUNT         40019
#define ID_DISKS_DRIVE2_UNMOUNT         40020
#define ID_DISKS_HARDDRIVE_UNMOUNT      40021
#define ID_QUICK                        40022
#define ID_IRQ                          40023
#define ID_FIRQ                         40024
#define ID_NMI                          40025
#define ID_CARTRIDGE_INSERT             40026
#define ID_FILE_LOAD                    40028
#define ID_SAVE_CONFIG                  40029
#define ID_CARTS_EJECT                  40030
#define ID_COPY_TEXT                    40034
#define ID_PASTE_TEXT                   40035
#define ID_PASTE_BASIC                  40036
#define ID_PASTE_BASIC_NEW              40037
#define ID_FLIP_ARTIFACTS               40038
#define IDC_REMEMBER_SIZE               40039
#define ID_CONFIGURE_OPTIONS            65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        171
#define _APS_NEXT_COMMAND_VALUE         40031
#define _APS_NEXT_CONTROL_VALUE         1255
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
